# Generated by Django 5.0.2 on 2025-07-20 20:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_initial'),
        ('contacts', '0002_initial'),
        ('meetings', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push Notification'), ('calendar', 'Calendar')], max_length=20)),
                ('scheduled_for', models.DateTimeField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['scheduled_for'],
            },
        ),
        migrations.CreateModel(
            name='MeetingTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('meeting_type', models.CharField(choices=[('internal', 'Internal Meeting'), ('client', 'Client Meeting'), ('sales', 'Sales Meeting'), ('support', 'Support Meeting'), ('training', 'Training'), ('review', 'Review Meeting'), ('other', 'Other')], max_length=20)),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('default_title', models.CharField(max_length=200)),
                ('default_description', models.TextField(blank=True)),
                ('default_agenda', models.TextField(blank=True)),
                ('default_reminder_minutes', models.PositiveIntegerField(default=15)),
                ('default_location_type', models.CharField(choices=[('physical', 'Physical Location'), ('virtual', 'Virtual Meeting'), ('hybrid', 'Hybrid')], default='virtual', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='meeting',
            name='agenda',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='all_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meeting',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='cases.case'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='contacts.company'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='contacts.contact'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='is_private',
            field=models.BooleanField(default=False, help_text='Private meetings are only visible to attendees'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meeting',
            name='location_type',
            field=models.CharField(choices=[('physical', 'Physical Location'), ('virtual', 'Virtual Meeting'), ('hybrid', 'Hybrid')], default='virtual', max_length=20),
        ),
        migrations.AddField(
            model_name='meeting',
            name='meeting_type',
            field=models.CharField(choices=[('internal', 'Internal Meeting'), ('client', 'Client Meeting'), ('sales', 'Sales Meeting'), ('support', 'Support Meeting'), ('training', 'Training'), ('review', 'Review Meeting'), ('other', 'Other')], default='internal', max_length=20),
        ),
        migrations.AddField(
            model_name='meeting',
            name='meeting_url',
            field=models.URLField(blank=True, help_text='Video conference URL'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='outcome',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='parent_meeting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recurring_instances', to='meetings.meeting'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='meeting',
            name='recurrence_rule',
            field=models.JSONField(blank=True, default=dict, help_text='RRULE format for recurring meetings'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='reminder_minutes',
            field=models.PositiveIntegerField(default=15, help_text='Minutes before meeting to send reminder'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='send_reminders',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled')], default='scheduled', max_length=20),
        ),
        migrations.AddField(
            model_name='meeting',
            name='timezone',
            field=models.CharField(default='UTC', max_length=50),
        ),
        migrations.CreateModel(
            name='CalendarIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('google', 'Google Calendar'), ('outlook', 'Outlook Calendar'), ('ical', 'iCal'), ('other', 'Other')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('sync_meetings', models.BooleanField(default=True, help_text='Sync meetings to external calendar')),
                ('sync_availability', models.BooleanField(default=True, help_text='Sync availability to external calendar')),
                ('api_key', models.CharField(blank=True, max_length=500)),
                ('api_secret', models.CharField(blank=True, max_length=500)),
                ('refresh_token', models.CharField(blank=True, max_length=500)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('sync_errors', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_integration', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Calendar Integration',
                'verbose_name_plural': 'Calendar Integrations',
            },
        ),
        migrations.CreateModel(
            name='MeetingAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('tentative', 'Tentative'), ('attended', 'Attended'), ('no_show', 'No Show')], default='invited', max_length=20)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('response_notes', models.TextField(blank=True)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='meetings.meeting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_attendances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MeetingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('color', models.CharField(default='#3B82F6', help_text='Hex color code', max_length=7)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_meeting_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Meeting categories',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='meeting',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='meetings.meetingcategory'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['start_time', 'end_time'], name='meetings_me_start_t_006dbd_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['organizer', 'start_time'], name='meetings_me_organiz_dadae7_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['status', 'start_time'], name='meetings_me_status_c95f40_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['meeting_type', 'start_time'], name='meetings_me_meeting_dea8b1_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['case', 'start_time'], name='meetings_me_case_id_c6cda7_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['contact', 'start_time'], name='meetings_me_contact_9b80be_idx'),
        ),
        migrations.AddField(
            model_name='meetingreminder',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='meetings.meeting'),
        ),
        migrations.AddField(
            model_name='meetingreminder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_reminders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meetingtemplate',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='meetings.meetingcategory'),
        ),
        migrations.AddField(
            model_name='meetingtemplate',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_meeting_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='meetingattendance',
            unique_together={('meeting', 'user')},
        ),
    ]
