# Generated by Django 5.0.2 on 2025-07-19 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('technical', 'Technical'), ('billing', 'Billing'), ('general', 'General'), ('feature_request', 'Feature Request'), ('bug_report', 'Bug Report'), ('account', 'Account'), ('security', 'Security')], default='general', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('new', 'New'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('waiting_customer', 'Waiting for Customer'), ('waiting_third_party', 'Waiting for Third Party'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('escalated', 'Escalated')], default='new', max_length=20)),
                ('source', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('web_form', 'Web Form'), ('chat', 'Chat'), ('portal', 'Customer Portal'), ('social_media', 'Social Media')], default='web_form', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('sla_hours', models.PositiveIntegerField(default=24, help_text='SLA in hours')),
                ('first_response_time', models.DurationField(blank=True, null=True)),
                ('resolution_time', models.DurationField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('email_thread_id', models.CharField(blank=True, help_text='Email thread identifier', max_length=255)),
                ('last_email_sent', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='case_attachments/')),
                ('filename', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField()),
                ('mime_type', models.CharField(max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_type', models.CharField(choices=[('internal', 'Internal Note'), ('customer', 'Customer Response'), ('system', 'System Note'), ('email', 'Email Response')], default='internal', max_length=20)),
                ('content', models.TextField()),
                ('is_internal', models.BooleanField(default=True, help_text='Internal note not visible to customer')),
                ('email_message_id', models.CharField(blank=True, max_length=255)),
                ('email_subject', models.CharField(blank=True, max_length=200)),
                ('email_from', models.EmailField(blank=True, max_length=254)),
                ('email_to', models.EmailField(blank=True, max_length=254)),
                ('email_cc', models.TextField(blank=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
