# Generated by Django 5.0.2 on 2025-07-19 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emails', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emails', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emailattachment',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='emails.email'),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='emails.email'),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='email',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='emails.emailtemplate'),
        ),
        migrations.AlterUniqueTogether(
            name='emailtemplate',
            unique_together={('name', 'template_type')},
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['status', 'email_type'], name='emails_emai_status_6d21b4_idx'),
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['case', 'created_at'], name='emails_emai_case_id_4f4d40_idx'),
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['user', 'created_at'], name='emails_emai_user_id_b6f4d1_idx'),
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['message_id'], name='emails_emai_message_48f464_idx'),
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['thread_id'], name='emails_emai_thread__f79da4_idx'),
        ),
    ]
