# Generated by Django 5.0.2 on 2025-07-19 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='archived',
            field=models.BooleanField(default=False, help_text='Whether the email is archived'),
        ),
        migrations.AddField(
            model_name='email',
            name='read',
            field=models.BooleanField(default=False, help_text='Whether the email has been read'),
        ),
        migrations.AddField(
            model_name='email',
            name='starred',
            field=models.BooleanField(default=False, help_text='Whether the email is starred'),
        ),
    ]
